---
driver:
  name: docker
  provision_command: sed -i '/tsflags=nodocs/d' /etc/yum.conf

provisioner:
  name: ansible_playbook
  ansible_yum_repo: "http://mirror.logol.ru/epel/6/x86_64/epel-release-6-8.noarch.rpm"
  hosts: localhost
  require_ruby_for_busser: false

platforms:
  - name: centos-6.6
    provisioner:
      playbook: tests/test.yml
      ansible_diff: true

suites:
  - name: default
