---
# tasks file for PostgreSQL

- name: Unexpected OS
  debug: msg="OS Family {{ ansible_os_family }} {{ ansible_architecture }} is not supported" fail=yes
  when: not ansible_os_family == "RedHat" or not ansible_architecture == "x86_64"

- name: Set OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_os_family }}.yml"
   - default.yml

- name: Install with Yum
  include: RedHat.yml
  when: (ansible_os_family == "RedHat" or ansible_os_family == "Centos") and ansible_architecture == "x86_64"
