# Exclude postgresql* on RHEL

- name: check rhnplugin.conf exists
  stat: path=/etc/yum/pluginconf.d/rhnplugin.conf
  register: rhnplugin_conf

# Real Redhat
- block:
  - name: Install | RHEL | Create symlink for repo fact gathering
    file: src=/etc/yum/pluginconf.d/rhnplugin.conf dest=/etc/ansible/facts.d/rhnplugin.fact state=link
    register: repo_fact_file

  - name: Install | RHEL | Gather repository facts
    setup: filter=ansible_local
    when: repo_fact_file|changed

  - name: Install | RHEL | Exclude packages
    ini_file:
      dest: /etc/yum/pluginconf.d/rhnplugin.conf
      section: main
      option: exclude
      value: >
        "{{ (ansible_local.baserepo.base.exclude | default('') |
        replace('postgresql*', '') | trim ~ ' postgresql* ') | trim }}"
      backup: yes
  when: rhnplugin_conf.stat is defined and rhnplugin_conf.stat.isfile

# CentOS with modified /etc/redhat-release something like 'Red Hat Enterprise Linux Server release 7.2 (Maipo)'
- name: Detected CentOS hiding as RedHat
  include: repo-exclude-centos.yml
  when: rhnplugin_conf.stat is defined and rhnplugin_conf.stat.exists == false
