#

- name: PostgreSQL | Make sure the PostgreSQL users are present
  postgresql_user:
    name: "{{item.name}}"
    password: "{{item.pass | default('pass')}}"
    state: present
    login_host: "{{item.host | default('localhost')}}"
    role_attr_flags: "{{item.role_attr_flags | default('LOGIN')}}"
    encrypted: "{{item.encrypted | default('no')}}"
  with_items: postgresql_users
  when: postgresql_users|length > 0
  no_log: True

- name: PostgreSQL | Update the users database privileges
  postgresql_user:
    name: "{{item.name}}"
    db: "{{item.db}}"
    priv: "{{item.priv | default('ALL')}}"
    state: present
    login_host: "{{item.host | default('localhost')}}"
  with_items: postgresql_user_privileges
  when: postgresql_user_privileges|length > 0

- name: PostgreSQL | Update the users object privileges
  postgresql_privs:
    role: "{{item.name}}"
    db: "{{item.db}}"
    priv: "{{item.priv | default('ALL')}}"
    state: present
    schema: "{{item.schema|default('public')}}"
    objs: "{{item.objs|default('')}}"
    type: "{{item.type|default('')}}"
    login_host: "{{item.host | default('localhost')}}"
  with_items: postgresql_user_object_privileges
  when: postgresql_user_object_privileges|length > 0
