---
# handlers file for PostgreSQL

- name: restart postgresql
  service: name=postgresql{{join_char | default("-")}}{{postgresql_version}} state=restarted

- name: start postgresql
  service: name=postgresql{{join_char | default("-")}}{{postgresql_version}} state=started
